version: '0.1'
services:
  sboard_db:
    image: mysql:8.4
    container_name: sboard_db
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: sboard
      MYSQL_USER: sboard
      MYSQL_PASSWORD: 1234
    volumes:
      - ./db/mysql/data:/var/lib/mysql
    networks:
      - springboot-mysql-net
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  sboard_app:
    build: .
    container_name: sboard_app
    restart: always
    ports:
      - 80:8085 
    depends_on:
      - sboard_db
    networks:
      - springboot-mysql-net
networks:
  springboot-mysql-net:
    driver: bridge
